[[ISSUERS]]
address = "r3i11zUhqgtGjuKucrRvTJ71PEGNaHdcKV"
name = "BananaX"

[[TOKENS]]
issuer = "r3i11zUhqgtGjuKucrRvTJ71PEGNaHdcKV"
currency = "BananaX"
name = "BananaX"
desc = "BananaX is a digital currency, developed specifically for the regulated gaming industry."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https:google.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
