[[ISSUERS]]
address = "rsywygqGBxCS2c5p4DbW3e52g5DrZ2ePe4"
name = "DARK PEPE"

[[TOKENS]]
issuer = "rsywygqGBxCS2c5p4DbW3e52g5DrZ2ePe4"
currency = "DPEPE"
name = "DARK PEPE"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
