[[ISSUERS]]
address = "raTQ7ohQkZ28yiAzEfT4wsWZ7xZDZzcbRX"
name = "HOTELX HOST XRP"

[[TOKENS]]
issuer = "raTQ7ohQkZ28yiAzEfT4wsWZ7xZDZzcbRX"
currency = "HOTELX"
name = "HOTELX HOST XRP"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
