[[ISSUERS]]
address = "rD9X3dgHTHf8pzeFHxfMHZAUUmKQVDrGtD"
name = "Nexia Agent"

[[TOKENS]]
issuer = "rD9X3dgHTHf8pzeFHxfMHZAUUmKQVDrGtD"
currency = "NEXIA"
name = "Nexia Agent"
desc = "Advanced AI agent specializing in crypto and memecoins trading."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
