[[ISSUERS]]
address = "rpE3FAd8kWSymXky7TfNAi1iMCwFCQRzW8"
name = "FLOODS FLOODING THE GATES"

[[TOKENS]]
issuer = "rpE3FAd8kWSymXky7TfNAi1iMCwFCQRzW8"
currency = "FLOODS"
name = "FLOODS FLOODING THE GATES"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
